In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path

checkpoint_filepath = Path("/Users/gwizdala/Documents/Data/pidnet_checkpoint.pt")

In [4]:
import torch

import models
from utils.utils import FullModel
from utils.criterion import OhemCrossEntropy, BoundaryLoss
from configs import config

semantic_seg_criterion = OhemCrossEntropy(
    ignore_label=255,
    thres=0.9,
    min_kept=100,
    weight=torch.tensor([1, 1])
)
bd_criterion = BoundaryLoss()

scale_factor = 8 / 16  # 8 is the default downsampling done by PIDNet
pidnet = models.pidnet.get_seg_model(config, pretrained=False)  # creates a pretrained model by default
model = FullModel(pidnet, semantic_seg_criterion, bd_criterion)

In [5]:
checkpoint = torch.load(checkpoint_filepath, map_location=torch.device("cpu"))
model.model.load_state_dict(checkpoint["state_dict"])

<All keys matched successfully>

In [9]:
pidnet.downsample_main.weight.data

tensor([[[[-0.0149,  0.9119],
          [ 0.8195, -0.6933]],

         [[ 0.0687,  0.0541],
          [-0.5914, -0.4559]]],


        [[[-0.0725,  0.2256],
          [ 0.1174, -0.2572]],

         [[-0.7448, -0.2600],
          [ 0.0495, -0.4430]]]])

In [10]:
pidnet.downsample_p.weight.data

tensor([[[[-0.4301,  0.6881],
          [ 0.5910, -0.0276]],

         [[-0.2193, -0.0379],
          [ 0.1633, -0.0193]]],


        [[[-0.0076,  0.7279],
          [ 0.7959,  0.5174]],

         [[ 0.3119, -0.0996],
          [-0.1274,  0.0975]]]])

In [11]:
pidnet.downsample_d.weight.data

tensor([[[[-1.3381, -0.2744],
          [ 0.3966, -0.0905]]]])